version: '3.3'

services:
  frontend:
    build:
      context: ./
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - jsonserver
  
  jsonserver:
    build:
      context: ./
      dockerfile: Dockerfile.jsonserver
    restart: on-failure
    ports:
      - 8081:8081